const authTypes = {
  FETCH_AUTH_OBJECT_START: "FETCH_AUTH_OBJECT_START",
  FETCH_AUTH_OBJECT_SUCCESS: "FETCH_AUTH_OBJECT_SUCCESS",
  FETCH_AUTH_OBJECT_FAILURE: "FETCH_AUTH_OBJECT_FAILURE"
};

export default authTypes;
