const authTypes = {
  FETCH_AUTH_OBJECT_START: "FETCH_AUTH_OBJECT_START",
  FETCH_AUTH_OBJECT_SUCCESS: "FETCH_AUTH_OBJECT_SUCCESS",
  FETCH_AUTH_OBJECT_FAILURE: "FETCH_AUTH_OBJECT_FAILURE",
  LOG_USER_IN_START: "LOG_USER_IN_START",
  LOG_USER_IN_SUCCESS: "LOG_USER_IN_SUCCESS",
  LOG_USER_IN_FAILURE: "LOG_USER_IN_FAILURE",
  LOG_USER_OUT_START: "LOG_USER_OUT_START",
  LOG_USER_OUT_SUCCESS: "LOG_USER_OUT_SUCCESS",
  LOG_USER_OUT_FAILURE: "LOG_USER_OUT_FAILURE"
};

export default authTypes;
