const surveyTypes = {
  FETCH_USER_SURVEYS_START: "FETCH_USER_SURVEYS_START",
  FETCH_USER_SURVEYS_SUCCESS: "FETCH_USER_SURVEYS_SUCCESS",
  FETCH_USER_SURVEYS_FAILURE: "FETCH_USER_SURVEYS_FAILURE",
  CREATE_SURVEY_START: "CREATE_SURVEY_START",
  CREATE_SURVEY_SUCCESS: "CREATE_SURVEY_SUCCESS",
  CREATE_SURVEY_FAILURE: "CREATE_SURVEY_FAILURE",
  CLEAN_SURVEYS_DATA_START: "CLEAN_SURVEYS_DATA_START",
  CLEAN_SURVEYS_DATA_SUCCESS: "CLEAN_SURVEYS_DATA_SUCCESS",
  CLEAN_SURVEYS_DATA_FAILURE: "CLEAN_SURVEYS_DATA_FAILURE"
};

export default surveyTypes;
