const paymentTypes = {
  REQUEST_PAYMENT_START: "REQUEST_PAYMENT_START",
  REQUEST_PAYMENT_SUCCESS: "REQUEST_PAYMENT_SUCCESS",
  REQUEST_PAYMENT_FAILURE: "REQUEST_PAYMENT_FAILURE"
};

export default paymentTypes;
